site_name: Paulo Lamounier
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.tabs.sticky
    - navigation.sections

nav:
    - Sobre: index.md
    - Tecnologias: tecnologias.md
    - Projetos: projetos.md
    - Experiências: experiencias.md
